### ISSUE TITLE
Unexpected kw_distinct token: "distinct"

### ISSUE THREAD

**Issue by xpportal-bmo** [oguimbal/pg-mem#14]
Hello again; found another feature that I hope you could implement.

This is running NestJS + typeorm + postgres

Example repo can be found here: https://github.com/xpportal-bmo/nestjs-pg-mem-test

Replication steps:
 - `npm install`
 - `npm run test`

Full error output:
```
● EntityTest › should find a user by email

    QueryFailedError: 💔 Your query failed to parse.
    This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
    If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error.

    👉 Failed query:

        SELECT DISTINCT "distinctAlias"."User_id" as "ids_User_id" FROM (SELECT "User"."id" AS "User_id", "User"."createdDate" AS "User_createdDate", "User"."updatedDate" AS "User_updatedDate", "User"."deletedDate" AS "User_deletedDate", "User"."email" AS "User_email", "User"."role" AS "User_role", "User"."accountId" AS "User_accountId", "User_account"."id" AS "User_account_id", "User_account"."createdDate" AS "User_account_createdDate", "User_account"."updatedDate" AS "User_account_updatedDate", "User_account"."deletedDate" AS "User_account_deletedDate", "User_account"."name" AS "User_account_name", "User_account"."type" AS "User_account_type" FROM "User" "User" LEFT JOIN "Account" "User_account" ON "User_account"."id"="User"."accountId" WHERE ( "User"."email" = 'test@domain.com' ) AND ( "User"."deletedDate" IS NULL )) "distinctAlias"  ORDER BY "User_id" ASC LIMIT 1;

    💀 Syntax error at line 1 col 8:

      SELECT DISTINCT
             ^
    Unexpected kw_distinct token: "distinct". Instead, I was expecting to see one of the following:

        - A "kw_from" token
        - A "star" token
        - A "lparen" token
        - A "kw_where" token
        - A "kw_group" token
        - A "kw_order" token
        - A "kw_not" token
        - A "kw_limit" token
        - A "kw_offset" token
        - A "kw_fetch" token
        - A "semicolon" token
        - A "op_plus" token
        - A "op_minus" token
        - A "word" token
        - A "kw_true" token
        - A "kw_false" token
        - A "kw_null" token
        - A "kw_case" token
        - A "float" token
        - A "int" token
        - A "string" token
        - A "eString" token
        - A "kw_current_catalog" token
        - A "kw_current_date" token
        - A "kw_current_role" token
        - A "kw_current_schema" token
        - A "kw_current_timestamp" token
        - A "kw_current_time" token
        - A "kw_localtimestamp" token
        - A "kw_localtime" token
        - A "kw_session_user" token
        - A "kw_user" token
        - A "kw_current_user" token
        - A "kw_any" token

      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at src/driver/postgres/PostgresQueryRunner.ts:220:30
      at Timeout._onTimeout (node_modules/pg-mem/src/adapters.ts:92:42)
```

**Comment by oguimbal** [comment]
Thanks for the report ! I'll fix that when I return from vacations :)

**Comment by BMO-tech** [comment]
Fantastic, thank you and enjoy your vacation :)

**Comment by oguimbal** [comment]
Should be ok with `pg-mem@1.5.2`
