### ISSUE TITLE
Problem with big decimal field on table creation

### ISSUE THREAD

**Issue by ashleighj** [oguimbal/pg-mem#149]
```
QueryFailedError: 🔨 Not supported 🔨 : The query you ran generated an AST which parts have not been read by the query planner. This means that those parts could be ignored:
    
        ⇨ .columns[6].dataType.config ([200,2])
    
    👉 pg-mem is work-in-progress, and it would seem that you've hit one of its limits.
    
    *️⃣ Failed SQL statement: 
    CREATE TABLE "public"."activity" (
      ... [ redacted ] ...
      "amount" numeric(200,2), 
      ... [ redacted ] ...
    );
    
        at new QueryFailedError (.../src/error/QueryFailedError.ts:9:9)
        at .../src/driver/postgres/PostgresQueryRunner.ts:188:30
        at Timeout._onTimeout (.../node_modules/pg-mem/src/adapters.ts:123:42)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7) 
```

**Comment by oguimbal** [comment]
Ah. Numeric precision is not implemented 😑

Thanks for the report. I'll add it to the (pretty long) todo list

**Comment by ashleighj** [comment]
Much appreciation for your work on this repo 🏆🏆

**Comment by alex996** [comment]
Would be great to have this. It's not only `numeric` by the way, same with `decimal` and `time` (like `time(0)`).

**Comment by marianotella** [comment]
@oguimbal Hi, I have the same problem. Have you added it to the todo list?

**Comment by SimonCockx** [comment]
+1. I use this datatype extensively for representing monetary values.

**Comment by SimonCockx** [comment]
> Hi, It would be easy to implement it naïvely, meaning that table creation would work, and usual operations as well.
> 
> BUT, doing that would not implement the actual behaviour of `numeric`, [which is quite complex](https://www.postgresql.org/docs/current/datatype-numeric.html).
> 
> This would mean that you could get inconsistent results (numbers would not be truncated to the defined numeric precision, "Infinity" and "NaN" would not exist, ...) 👉 These numbers would not behave exactly as actual postgres `numeric` values, and your tests might not behave as expected 🤷‍♂️
> 
> So, just a quick poll (anyone can answer): Vote 👍 if it would be of any use to implement that naïve version Vote 👎 if it's useless, and you want to wait until I have enough time to implement a real `numeric` type

That would definitely be useful! Right now this small limitation makes it impossible for me to use this really cool library, but I think a naive version would already suffice for most use cases. And if it doesn't suffice for someone, that person is always free to create a new ticket I guess. :)

**Comment by oguimbal** [comment]
This workaround should work as well:

```typescript
db.public.interceptQueries(sql => {
    const newSql = sql.replace(/\bnumeric\s*\(\s*\d+\s*,\s*\d+\s*\)\b/, 'float');
    if (sql !== newSql) {
         return db.public.many(newSql);
    }
    // proceed to actual SQL execution for other requests.
    return null;
});
```

This should replace all `numeric(x,y)` with `float`

**Comment by SimonCockx** [comment]
@alex996 Okay, you have a point. It might be preferable to fail fast in every case as long as it doesn't work for some cases. I guess that a the workaround such as proposed by @oguimbal might temporarily suffice. Let me try it out...

**Comment by SimonCockx** [comment]
> Now that I think about it, this workaround should work as well:
> 
> ```ts
> const db = newDb();
> db.public.interceptQueries(sql => {
>     const newSql = sql.replace(/\bnumeric\s*\(\s*\d+\s*,\s*\d+\s*\)\b/a, 'float');
>     if (sql !== newSql) {
>          return db.public.many(newSql);
>     }
>     // proceed to actual SQL execution for other requests.
>     return null;
> });
> ```
> 
> This should replace all `numeric(x,y)` instances in the executed queries with `float`.
> 
> And at least, if you copy-paste that, you know that you're doing something wrong for your numeric types 😄
> 
> disclaimer: not tested :)
> 
> disclaimer 2: dont try to insert strings that contain `numeric(x,y)` 😅
> 
> Tell me if it works... (it is in fact equivalent to the naive implementation) If it does, i'll wait

I needed to make two small changes to the regex. Firstly, `/a` should be `/g` (i.e., for a global search). Secondly, the last `\b` should be removed because the `\)` token is not considered the end of a word. The following code worked!

```
db.public.interceptQueries((sql) => {
    const newSql = sql.replace(/\bnumeric\s*\(\s*\d+\s*,\s*\d+\s*\)/g, 'float');
    if (sql !== newSql) {
        return db.public.many(newSql);
    }
    // proceed to actual SQL execution for other requests.
    return null;
});
```
Thanks @oguimbal!

**Comment by oguimbal** [comment]
You're welcome :) Thanks for the fix. (I amended my answer with it)
