### ISSUE TITLE
Partial Indexes not working with unique index where column value is null

### ISSUE THREAD

**Issue by jshanman** [oguimbal/pg-mem#160]
I saw in this issue that support for Partial Indexes was added: https://github.com/oguimbal/pg-mem/issues/89

However, if you insert null as a value for a column with a unique index, in actual postgres it works since `null` values are not considered in unique value validation, but `pg-mem` does appear to include them when validating uniques and prevents the 2nd row from inserting with a value of `null`.

Example SQL for postgres (works as expected against an actual postgres engine)
```sql
create table "test_table" (
  "id" character varying(36) NOT NULL, 
  "unique_data" character varying(36), 
  "deleted_at" timestamp without time zone,
  CONSTRAINT "PK_test_table_id"
  PRIMARY KEY ("id")  
);

CREATE UNIQUE INDEX "UXtest_table_unique_data" ON "public"."test_table" ("unique_data") WHERE deleted_at IS NULL;

insert into test_table ("id", "unique_data", "deleted_at") VALUES('1', default, default );
insert into test_table ("id", "unique_data", "deleted_at") VALUES('2', default, default );
```

Example jest / nestjs / typeorm / pg-mem test (NOT WORKING but I'd expect it to)
```typescript
// "@nestjs/testing": "^8.0.0",
import { Test, TestingModule } from '@nestjs/testing';
// "@nestjs/typeorm": "^8.0.2",
import { getRepositoryToken } from '@nestjs/typeorm';
// "typeorm": "^0.2.37",
import { Repository, Connection, Entity,
  Column,
  PrimaryColumn,
  Index,
  DeleteDateColumn, 
} from 'typeorm';
// "pg-mem": "^2.0.2",
import { newDb } from 'pg-mem';

@Index('UXtest_table_unique_data', ['uniqueData'], {
  unique: true,
  where: 'deleted_at IS NULL'
})
@Entity()
export class TestEntity {
  @PrimaryColumn({ length: 36 })
  id: string;

  @Column({ length: 36, name: 'unique_data', nullable: true })
  uniqueData?: string;

  @DeleteDateColumn({
    name: 'deleted_at',
    type: 'timestamp without time zone',
    nullable: true,
  })
  deletedAt: Date;
}

describe('ExamplePartialUniqueProblemWithPgMem', () => {
  let testRepo: Repository<TestEntity>, connection: Connection;

  beforeEach(async () => {
    // create a postgres memory db
    const db = newDb({});

    // define current_database
    // work around typeorm calling 'current_database' function
    db.public.registerFunction({
      implementation: () => 'test',
      name: 'current_database',
    });

    // create a Typeorm connection
    connection = await db.adapters.createTypeormConnection({
      type: 'postgres',
      entities: [TestEntity],
    });

    // create tables
    await connection.synchronize();
    testRepo = connection.getRepository(TestEntity);
  });

  afterEach(async () => {
    await connection.close();
  });

  it('create 2 test entries will null for a unique column', async () => {

    await testRepo.save({
      id: '1',
    });

    await testRepo.save({
      id: '2',
    });

    // get id 2
    const record2 = await testRepo.findOne('2');

    expect(record2.id).toEqual('2');
  });
});

```

Running this test produces this output for me

```bash
npm run test -- test.spec

> test@0.0.1 test
> jest --testResultsProcessor=jest-junit "test.spec"

 FAIL  src/talent/test.spec.ts (8.483 s)
  ExamplePartialUniqueProblemWithPgMem
    ✕ create 2 test entries will null for a unique column (241 ms)

  ● ExamplePartialUniqueProblemWithPgMem › create 2 test entries will null for a unique column

    QueryFailedError: ERROR: insert into "test_entity" (id, unique_data, deleted_at) values ($1, $2, $3) returning "unique_data" - duplicate key value violates unique constraint "test_entity_pkey"
    DETAIL: Key (unique_data)=() already exists.

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: INSERT INTO "test_entity"("id", "unique_data", "deleted_at") VALUES ('2', DEFAULT, DEFAULT) RETURNING "deleted_at";

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at QueryFailedError.TypeORMError [as constructor] (error/TypeORMError.ts:7:9)
      at new QueryFailedError (error/QueryFailedError.ts:9:9)
      at PostgresQueryRunner.<anonymous> (driver/postgres/PostgresQueryRunner.ts:258:19)
      at step (../node_modules/tslib/tslib.js:143:27)
      at Object.throw (../node_modules/tslib/tslib.js:124:57)
      at rejected (../node_modules/tslib/tslib.js:115:69)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        8.542 s, estimated 9 s
Ran all test suites matching /test.spec/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by oguimbal** [comment]
Wow, nice catch.
That's actually a really weird behaviour 😅 

`SELECT * FROM test_table WHERE deleted_at IS NULL`  will return the row, but neither the index clauses `WHERE deleted_at IS NULL` nor `WHERE deleted_at NOTNULL`  will take take it into account. Rows with default values will fall in a gap where they are invisible, and cannot be indexed. Really weird. But hey, if that's how pg works 🤷 Okay.

**Comment by oguimbal** [comment]
Fix shipped with `pg-mem@2.1.0` 

I refactored a bit how `default` values work. Even if pg-mem is quite heavily tested and everything seems OK, please keep an eye open if you see weird behaviours on default values / null checks !

**Comment by oguimbal** [comment]
Okay, my bad, do not install 2.1.0, I misunderstood the way pg works. Pushing a fix soon.

**Comment by oguimbal** [comment]
Fixed 👉   `pg-mem@2.1.2` 

For the record: This turns out to have nothing to do with partial indexes... indices are just ignoring null values.
Which is less weird :)


For instance, this works:

```sql
drop table if exists test_table;   
   
create table "test_table" (
 "id" text not null primary key,
 "unique_data" text default null
);

CREATE UNIQUE INDEX ON test_table (unique_data);

insert into test_table ("id", "unique_data") VALUES('1', default);
insert into test_table ("id", "unique_data") VALUES('2', default);
insert into test_table ("id", "unique_data") VALUES('3', null);
insert into test_table ("id", "unique_data") VALUES('4', null);
```

it even ignores nulls in compound keys... meaning that this also works:

```sql
create table "test_table" (
 "u1" text ,
 "u2" text 
);

CREATE UNIQUE INDEX ON test_table (u1, u2);

insert into test_table ("u1", "u2") VALUES('1', default);
insert into test_table ("u1", "u2") VALUES('1', null);
insert into test_table ("u1", "u2") VALUES('1', null);
```

**Comment by jshanman** [comment]
I'll test it out, thanks for the fast followup!

**Comment by jshanman** [comment]
Confirmed fixed!
