### ISSUE TITLE
unable to use the alias in the group by block 

### ISSUE THREAD

**Issue by harin10** [oguimbal/pg-mem#176]
# Describe the bug

I have script where the columns  are custome built using a case statements and I am aliasing them to custom name 

ISSUE 1 : 
select case
                               when type_lk.frml_nfrml_ind = 'I' then 'NOT_FORMAL'
                               when type_lk.frml_nfrml_ind = 'F' then 'FORMAL'
                               else null
                               end   as timtim, ....
from join multiple tables 
group by case
                               when type_lk.frml_nfrml_ind = 'I' then 'NOT_FORMAL'
                               when type_lk.frml_nfrml_ind = 'F' then 'FORMAL'
                               else null
                               end,  .... 

ISSUE 2: 
select case
                               when type_lk.frml_nfrml_ind = 'I' then 'NOT_FORMAL'
                               when type_lk.frml_nfrml_ind = 'F' then 'FORMAL'
                               else null
                               end   as timtim, ....
from join multiple tables 
group by timtim,.... 

```
(pg-mem tries to throw nice error messages when possible... so paste it here if you have one !)
```

# To Reproduce

```sql

"If possible, paste here (including create table statements) a query that fails on https://oguimbal.github.io/pg-mem-playground/, but suceeds when ran on an actual PG database"

```

# pg-mem version pg-mem": "^2.0.0"

(paste your pg-mem version here)

(nb: the version in your package.json version is often not precise enough... please run "cat ./node_modules/pg-mem/package.json | grep version" to tell which minor version is actually installed)

Error on case 1 :  
Unable to obtain outcome types: TypeError: this.groupIndex.iterateKeys is not a function or its return value is not iterable\n\n💥 This is a nasty error, which was unexpected by pg-mem. Also known \"a bug\" 😁 Please file an issue 

Error on case 2: 

\"star_disposition_active_flag\" does not exist\n\n🐜 This seems to be an execution error, which means that your request syntax seems okay,\nbut the resulting statement cannot be executed → Probably not a pg-mem error.\n\n*️⃣

**Comment by foysalit** [comment]
Seeing the same issue myself.

Details:
==========
I want to group by a column and count number of entries per column value so  I built that using `typeorm` query-builder and the resulting query looks like this `SELECT badge, COUNT(*) AS "count" FROM "badge" "Badge" GROUP BY "badge" ORDER BY "count" DESC` which works great when ran on Postgres but breaks and throws the following error when ran on pg-mem:
```
    QueryFailedError: TypeError: this.groupIndex.iterateKeys is not a function or its return value is not iterable

    💥 This is a nasty error, which was unexpected by pg-mem. Also known "a bug" 😁 Please file an issue !

    *️⃣ Failed SQL statement: SELECT badge, COUNT(*) AS "count" FROM "badge" "Badge" GROUP BY "badge" ORDER BY "count" DESC;

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at QueryFailedError.TypeORMError [as constructor] (src/error/TypeORMError.ts:7:9)
      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at PostgresQueryRunner.<anonymous> (src/driver/postgres/PostgresQueryRunner.ts:258:19)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.throw (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at rejected (node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
```
