### ISSUE TITLE
Register Function does not recognize DataType.array

### ISSUE THREAD

**Issue by mrriskalyze** [oguimbal/pg-mem#189]
# Describe the bug
When registering a function, `DataType.array` is not recognized as a valid type in either the `args` or the `returns` fields.  It is defined in the enum, but do I need to make a custom type of some sort for `registerFunction` to both accept and return an array?

```
type "array" does not exist

      45 |     });
      46 |
    > 47 |     this.db.public.registerFunction({
         |                    ^
      48 |       name: 'foo',
      49 |       args: [DataType.text, DataType.array],
      50 |       returns: DataType.text,

      at chk (../node_modules/pg-mem/src/schema/schema.ts:221:23)
      at DbSchema.getType (../node_modules/pg-mem/src/schema/schema.ts:243:16)
      at DbSchema.getType (../node_modules/pg-mem/src/schema/schema.ts:213:25)
      at DbSchema.getTypePub (../node_modules/pg-mem/src/schema/schema.ts:200:21)
      at ../node_modules/pg-mem/src/schema/schema.ts:494:36
          at Array.map (<anonymous>)
      at DbSchema.registerFunction (../node_modules/pg-mem/src/schema/schema.ts:491:29)
```
Implementation
```
import { DataType, IMemoryDb, newDb } from "pg-mem";
export class MockDb {
  private db = newDb();
  constructor(){
   this.db.public.registerFunction({
      name: 'foo',
      args: [DataType.text, DataType.array],
      returns: DataType.text,
      implementation: () => {
        return 'Sample Data';
      }
    });

   this.db.public.registerFunction({
      name: 'bar',
      args: [DataType.text, DataType.integer],
      returns: DataType.array,
      implementation: () => {
        return ['Sample', 'Array'];
      }
    });

  public getDb(): IMemoryDb {
    return this.db;
  }
}

```

# pg-mem version

2.3.2

**Comment by oguimbal** [comment]
Hi !

The `DataType` enum is a shortcut for well known types.
To get the `int[]` type, for instance, you'll have to do this:

```typescript
const intArray = myDb.public.getType(DataType.integer).asArray();
```

Then, you will be able to use `intArray` as your return type.
```

**Comment by oguimbal** [comment]
Anytime.
Thanks !
