### ISSUE TITLE
Knex query run in a jest test returns boolean as string "1" or "0"

### ISSUE THREAD

**Issue by springbok** [oguimbal/pg-mem#195]
# Describe the bug

Probably not a bug just me not understanding what is happening. I'm writing tests for some knex resolvers in a graphql app accessing the following table:
```
    .createTable('lookups', function (table: CreateTableBuilder) {
      table.increments()
      table.boolean('active').notNullable().defaultTo(true)
      table.string('description').notNullable()
      table.string('type').notNullable()
      table.unique(['description', 'type']);
      table.timestamps(true, true)
    })
```
When I call the graphql endpoint via my app I get the following SQL generated:
```
insert into "lookups" ("description", "type") values ('Test', 'Categories') returning *
```
And the following is returned:
```
Lookup {
  description: 'Test',
  type: 'Categories',
  createdAt: '2022-03-04T06:14:41.424Z',
  id: 11,
  active: true,
  updatedAt: '2022-03-04T06:14:41.427Z'
}
```
I then run the same code via jest and get the same SQL generated but the result I get back is:
```
   Lookup {
      description: 'Test',
      type: 'Categories',
      createdAt: '2022-03-04T06:32:28.373Z',
      id: 10,
      active: '1',
      updatedAt: '2022-03-04T06:32:28.246Z'
    }
```
The boolean value does not get converted to true and is returned as '1', the error I get from graphql
```
   lookup:  {
      errors: [
        {
          message: 'Boolean cannot represent a non boolean value: "1"',
          locations: [Array],
          path: [Array]
        }
      ],
      data: { addLookup: null }
    }
```

# To Reproduce

```insert into "lookups" ("description", "type") values ('Test', 'Categories') returning *

# pg-mem version

2.3.3

**Comment by samson501** [comment]
I'm having a similar issue using Jest, slightly different reproduction but I believe the root cause is the same. I cannot insert a boolean value into the database, it must be a `"true"` or `"false"` string.

```
 FAIL  __tests__/api/process-log-files/files-one.ts (8.711 s)
  ● /api/process-log-files › should process one file

    TypeError: rawStr.toLowerCase is not a function

    💥 This is a nasty error, which was unexpected by pg-mem. Also known "a bug" 😁 Please file an issue !

    *️⃣ Failed SQL statement: 
          INSERT INTO venues 
            (id, premium_enabled) 
          VALUES ($1, $2);

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:
```

This is the Full Stacktrace

```
      at value.setConversion.toBool.toBool (node_modules/pg-mem/src/datatypes/datatypes.ts:336:56)
      at Evaluator.val (node_modules/pg-mem/src/evaluator.ts:125:28)
      at Evaluator.get (node_modules/pg-mem/src/evaluator.ts:220:21)
      at Insert.performMutation (node_modules/pg-mem/src/execution/records-mutations/insert.ts:149:62)
      at Insert._doExecuteOnce (node_modules/pg-mem/src/execution/records-mutations/mutation-base.ts:60:29)
      at Insert.enumerate (node_modules/pg-mem/src/execution/records-mutations/mutation-base.ts:72:29)
          at enumerate.next (<anonymous>)
      at SelectExec.execute (node_modules/pg-mem/src/execution/select.ts:279:41)
      at node_modules/pg-mem/src/execution/statement-exec.ts:208:42
      at pushExecutionCtx (node_modules/pg-mem/src/utils.ts:404:16)
      at node_modules/pg-mem/src/execution/statement-exec.ts:196:54
      at StatementExec.niceErrors (node_modules/pg-mem/src/execution/statement-exec.ts:226:20)
      at StatementExec.executeStatement (node_modules/pg-mem/src/execution/statement-exec.ts:196:21)
      at Bound.doExecute (node_modules/pg-mem/src/schema/prepared.ts:248:25)
          at doExecute.next (<anonymous>)
      at Bound.executeAll (node_modules/pg-mem/src/schema/prepared.ts:226:30)
      at executeAll (__tests__/api/process-log-files/files-one.ts:18:49)
      at Object.queryHub (__tests__/api/process-log-files/files-one.ts:456:5)
```

# To Reproduce
```
// Create table
db.prepare(
`create table venues
(
  id                      varchar(255) default NULL::character varying not null
      primary key,
  premium_enabled         boolean      default false
)`)

db.executeAll()

// Insert a boolean in table
db.prepare(
 `INSERT INTO venues 
    (id, premium_enabled) 
  VALUES ($1, $2)`

db.bind(
  ["SOMEID",  true]
)

db.executeAll()
```
