### ISSUE TITLE
[pg-mem x typeorm] QueryFailedError: column "columns.table_name" does not exist

### ISSUE THREAD

**Issue by FlorianVeys** [oguimbal/pg-mem#291]
# Describe the bug

Hello, I'm not able to use pg-mem with the last version of typeorm and pg-mem. 
When the test is executed, an error is thrown saying `QueryFailedError: column "columns.table_name" does not exist`

```
QueryFailedError: column "columns.table_name" does not exist

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
        but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: SELECT columns.*, pg_catalog.col_description(('"' || table_catalog || '"."' || table_schema || '"."' || table_name || '"')::regclass::oid, ordinal_position) AS description, ('"' || "udt_schema" || '"."' || "udt_name" || '"')::"regtype" AS "regtype", pg_catalog.format_type("col_attr"."atttypid", "col_attr"."atttypmod") AS "format_type" FROM "information_schema"."columns" LEFT JOIN "pg_catalog"."pg_attribute" AS "col_attr" ON "col_attr"."attname" = "columns"."column_name" AND "col_attr"."attrelid" = ( SELECT "cls"."oid" FROM "pg_catalog"."pg_class" AS "cls" LEFT JOIN "pg_catalog"."pg_namespace" AS "ns" ON "ns"."oid" = "cls"."relnamespace" WHERE "cls"."relname" = "columns"."table_name" AND "ns"."nspname" = "columns"."table_schema" ) WHERE ("table_schema" = 'public' AND "table_name" = 'photo');

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at PostgresQueryRunner.query (src/driver/postgres/PostgresQueryRunner.ts:299:19)
          at async Promise.all (index 0)
      at PostgresQueryRunner.loadTables (src/driver/postgres/PostgresQueryRunner.ts:3361:32)
      at PostgresQueryRunner.getTables (src/query-runner/BaseQueryRunner.ts:158:29)
      at RdbmsSchemaBuilder.build (src/schema-builder/RdbmsSchemaBuilder.ts:92:13)
      at DataSource.synchronize (src/data-source/DataSource.ts:318:9)
      at setupInMemoryDb (index.test.ts:26:5)
      at Object.<anonymous> (index.test.ts:36:32)
```

# To Reproduce

Dependencies :
```
"jest": "^29.3.1",
"pg": "^8.8.0",
"pg-mem": "^2.6.4",
"reflect-metadata": "^0.1.13",
"typeorm": "^0.3.11"
```

Entity :
```
import { Entity, Column, PrimaryColumn } from "typeorm";

@Entity()
export class Photo {
  @PrimaryColumn()
  id!: number;

  @Column()
  name!: string;
}
```

Migration associate : 

```
import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1673261303001 implements MigrationInterface {
    name = 'Migration1673261303001'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "photo" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_723fa50bf70dcfd06fb5a44d4ff" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "photo"`);
    }

}
```

Test file : 
```
import { IBackup, IMemoryDb, newDb } from "pg-mem";
import { DataSource } from "typeorm";
import { PostgresConnectionOptions } from "typeorm/driver/postgres/PostgresConnectionOptions";
import { databaseConfig } from "./datasource";

describe("test", () => {
  async function setupInMemoryDb(
    connectionOptions: PostgresConnectionOptions
  ): Promise<[IMemoryDb, DataSource]> {
    const inMemoryPG = newDb();

    inMemoryPG.public.registerFunction({
      name: "version",
      implementation: () => "15",
    });

    inMemoryPG.public.registerFunction({
      name: "current_database",
      implementation: () => "test",
    });

    const datasource: DataSource =
      await inMemoryPG.adapters.createTypeormDataSource(connectionOptions);

    await datasource.initialize();
    await datasource.synchronize();

    return [inMemoryPG, datasource];
  }

  let inMemoryDb: IMemoryDb;
  let dbBackup: IBackup;
  let dataSource: DataSource;

  beforeAll(async () => {
    [inMemoryDb, dataSource] = await setupInMemoryDb(databaseConfig);
    dbBackup = inMemoryDb.backup();
  });

  beforeEach(async () => {
    dbBackup.restore();
  });

  it("test", async () => {
    await dataSource.query(`
        INSERT INTO "photo" (id, name)
        VALUES
        (1, 'test')
    `);

    expect(await dataSource.query(" SELECT * FROM photo")).toBe([
      { id: 1, name: "test" },
    ]);
  });
});

```

# pg-mem version
2.6.4

Thanks in advance for the help 🙏

**Comment by oguimbal** [comment]
Hi !

The below works for me.

```typescript

@Entity()
export class Photo {
    // added types, so the Typeorm can create them with the right types
    @PrimaryColumn({ type: 'integer' }) 
    id!: number;

    @Column({ type: 'text' })
    name!: string;
}

describe("test", () => {
    let dataSource: DataSource;
    beforeEach(async () => {
        const db = newDb();
        db.public.registerFunction({
            implementation: () => 'test',
            name: 'version'
        });
        db.public.registerFunction({
            implementation: () => 'test',
            name: 'current_database'
        });
        db.createSchema('test');

        dataSource = await db.adapters.createTypeormDataSource({
            type: 'postgres',
            name: 'default',
            host: 'localhost',
            port: 5432,
            schema: 'public',
            database: 'test',
            username: 'postgres',
            password: 'postgres',
            entities: [Photo],
        });
        await dataSource.initialize(); // added this
        await dataSource.synchronize();
    });

    afterEach(async () => {
        await dataSource.destroy()
    })

    it("test", async () => {
        await dataSource.query(`
        INSERT INTO "photo" (id, name)
        VALUES
        (1, 'test')
    `);

        expect(await dataSource.query(" SELECT * FROM photo")).toBe([
            { id: 1, name: "test" },
        ]);
    });
});

```


Does it work for you ?

**Comment by andrecarlucci** [comment]
Just if someone has the same problem in the future:
I had the same error and adding the "schema" (creation and configuration) fixed it.
