### ISSUE TITLE
Can't use table in specific schema with Knex adapter

### ISSUE THREAD

**Issue by skeet70** [oguimbal/pg-mem#303]
# Describe the bug

I'm trying to import a test fixture DB dump of a production schema and make calls using the Knex adapter. Unfortunately I'm not seeing a way to specify a schema other than public to use with the Knex adapter, and it seems to default to `public`.

```
select count(*) from "organization" where "domain" = $1 and "name" = $2 - relation "organization" does not exist

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
        but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: select count(*) from "organization" where "domain" = 'test-orgdomain-icl' and "name" = 'test org';

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at chk (../../node_modules/pg-mem/src/schema/schema.ts:264:23)
      at DbSchema.chk [as getObject] (../../node_modules/pg-mem/src/schema/schema.ts:286:16)
      at getObject (../../node_modules/pg-mem/src/execution/select.ts:225:43)
      at getSelectable (../../node_modules/pg-mem/src/execution/select.ts:98:24)
      at buildRawSelectSubject (../../node_modules/pg-mem/src/execution/select.ts:165:15)
      at buildRawSelect (../../node_modules/pg-mem/src/execution/select.ts:55:20)
      at buildSelect (../../node_modules/pg-mem/src/execution/select.ts:35:20)
      at new buildWithable (../../node_modules/pg-mem/src/execution/select.ts:270:67)
      at StatementExec._getExecutor (../../node_modules/pg-mem/src/execution/statement-exec.ts:82:24)
      at _getExecutor (../../node_modules/pg-mem/src/execution/statement-exec.ts:181:52)
      at act (../../node_modules/pg-mem/src/parser/context.ts:11:20)
      at ../../node_modules/pg-mem/src/execution/statement-exec.ts:180:40
      at act (../../node_modules/pg-mem/src/parser/context.ts:11:20)
      at ../../node_modules/pg-mem/src/execution/statement-exec.ts:179:36
      at act (../../node_modules/pg-mem/src/parser/context.ts:11:20)
      at ../../node_modules/pg-mem/src/execution/statement-exec.ts:178:29
      at StatementExec.act [as niceErrors] (../../node_modules/pg-mem/src/execution/statement-exec.ts:221:20)
      at StatementExec.niceErrors [as compile] (../../node_modules/pg-mem/src/execution/statement-exec.ts:154:21)
      at DbSchema.compile (../../node_modules/pg-mem/src/schema/schema.ts:122:36)
          at queries.next (<anonymous>)
      at DbSchema.r [as query] (../../node_modules/pg-mem/src/schema/schema.ts:79:20)
      at MemPg.query (../../node_modules/pg-mem/src/adapters/adapters.ts:100:76)
      at query (../../node_modules/knex/lib/dialects/postgres/index.js:226:18)
      at Client_PG._query (../../node_modules/knex/lib/dialects/postgres/index.js:225:12)
      at _query (../../node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
      at Client_PG.executeQuery [as query] (../../node_modules/knex/lib/client.js:146:12)
      at Runner.query (../../node_modules/knex/lib/execution/runner.js:123:36)
      at query (../../node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
      at Runner.cb [as ensureConnection] (../../node_modules/knex/lib/execution/runner.js:300:20)
      at Runner.run (../../node_modules/knex/lib/execution/runner.js:30:19)
```

# To Reproduce

Production DB client:

```ts
 * Create our shared db client with the configured connection.
 */
export const dbclient: Knex = knex({
    client: "pg",
    connection: {
        host: process.env.DB_URL,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_NAME,
        ssl: process.env.DB_SSL === "true",
    },
});
```

Test pg-mem DB client:

```ts
const mem = newDb();

mem.public.registerFunction({name: "current_timestamp", args: [DataType.integer], returns: DataType.timestamp, implementation: () => Date.now(), impure: true});
mem.public.none(fs.readFileSync(path.resolve(__dirname, "./applicationschema.sql"), "utf-8"));

console.log(mem.getSchema("applicationschema").getTable("organization").listIndices());
export const dbclient = mem.adapters.createKnex() as typeof import("knex");
```

console output implying that the `applicationschema` exists:

```console
  console.log
    [
      {
        name: 'organization_domain_name_key',
        expressions: [ 'domain', 'name' ]
      },
      { name: 'organization_pkey', expressions: [ 'id' ] }
    ]
      at Object.<anonymous> (__mocks__/db.ts:10:9)
```

I'd expect a way to configure the adapter and tell it a schema all queries are going to be in the context of. It's possible that it could be expected/pulled from `knexConfig.connection`, which right now looks to be tossed.

# pg-mem version

2.6.6

**Comment by skeet70** [comment]
I tried adding `withSchema("applicationschema")` to each `dbclient` call under test and still ran into

```console
    insert into "applicationschema"."organization" ("domain", "name") values ($1, $2) returning "id" - relation "organization_id_seq" does not exist
```

though that sequence was created in the `applicationschema.sql`:

```sql
CREATE SEQUENCE applicationschema.organization_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
```

and there were no errors about it not being created when running the import.
