### ISSUE TITLE
[pg_indexes] Support for dropping a foreign key constraint in a typeorm migration

### ISSUE THREAD

**Issue by krumft** [oguimbal/pg-mem#307]
Our application is using `typeorm` version `0.3.11` against a Postgres database, and we maintain our DB schema in TypeScript migrations. These are getting executed successfully against the 'real' Postgres db.

We have recently started adopting `pg-mem` to write unit tests (well ... ok, integration tests) for our entities and repositories. We are using version `2.6.8` of the package.

One of our migrations drops a column `col` in table `t` which has a foreign key constraint `cons` on it. The migration first executes an `ALTER TABLE t DROP CONSTRAINT cons` statement and then an `ALTER TABLE t DROP COLUMN col` statement. When executed against the in-memory `pg-mem` database, that migration fails with:
```
cannot drop an index that does not exist
```
I believe that this happens for the index that `typeorm` has implicitly created for the relationship modelled by that foreign key column, which in the entity is decorated with `@OneToOne` and `@JoinColumn()` on the column in question. Please note that there is no explicit `DROP INDEX` statement in the migration that fails, neither there is a `CREATE INDEX` on the earlier migration that defines the foreign key column.

My guess for the root cause of the problem is that `typeorm` consults the `pg_indexes` in Postgres table to check and delete indexes, which in the case of `pg-mem` is not yet supported.

We have worked the problem around with this hack:
```
.interceptQueries((queryText) => {
	if (queryText.includes('DROP CONSTRAINT')) {
		return [];
	}
	return null;
});
```

Still, it would be great if `pg-mem` has first class support for indexes as in supporting the `pg_indexes` abstraction of Postgres, which will allow `typeorm` to drop foreign key constraints without such hacks.

**Comment by krumft** [comment]
It is somewhat interesting to add that `CREATE INDEX` and `DROP INDEX` statements in our migrations are successfully executed against `pg-mem`, we only have issues with `DROP CONSTRAINT`.

**Comment by krumft** [comment]
Just to add that our migrations do have multiple `CREATE INDEX` and `DROP INDEX` statements in them, and they are all successful against `pg-mem`. So it is not completely clear that the issue is in `pg_indexes`.

**Comment by krumft** [comment]
**Update**: I have confirmed by exploring the case of the real Postgres database that when the initial migration that defines the table got executed:
1. `typeorm` didn't issue any explicit `CREATE INDEX` statements against the database;
2.  the migration has created an entry in `pg_indexes` by the name of `REL_<uuid>`.

So implementing the unique constraint by creating an index for it appears to be an implementation detail of Postgres.

**Comment by krumft** [comment]
I have managed to reproduce the problem with a minimalistic test:
```
	it('test dropping unique constraint', async () => {
		db.public.query(
			'CREATE TABLE "table" ("id" character varying NOT NULL, "col" character varying, CONSTRAINT "REL_constraint" UNIQUE ("col"), CONSTRAINT "PK_constraint" PRIMARY KEY ("id"))',
		);
		db.public.query('ALTER TABLE "table" DROP CONSTRAINT "REL_constraint"');
		db.public.query('ALTER TABLE "table" DROP COLUMN "col"');
	});
```
which fails with:
```
Error: Cannot drop index that does not belong to this table: REL_constraint

🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

*️⃣ Failed SQL statement: ALTER TABLE "table" DROP COLUMN "col";

👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

    at MemoryTable.dropIndex (.../node_modules/pg-mem/src/table.ts:663:19)
    at ColRef.drop (.../node_modules/pg-mem/src/column.ts:195:24)
    at Alter.execute (.../node_modules/pg-mem/src/execution/schema-amends/alter.ts:54:29)
    at .../node_modules/pg-mem/src/execution/statement-exec.ts:203:42
    at pushExecutionCtx (.../node_modules/pg-mem/src/utils.ts:391:16)
    at .../node_modules/pg-mem/src/execution/statement-exec.ts:192:54
    at StatementExec.niceErrors (.../node_modules/pg-mem/src/execution/statement-exec.ts:221:20)
    at StatementExec.executeStatement (.../node_modules/pg-mem/src/execution/statement-exec.ts:192:21)
    at DbSchema.queries (.../node_modules/pg-mem/src/schema/schema.ts:130:45)
    at queries.next (<anonymous>)

```

**Comment by krumft** [comment]
After some debugging it seems that the root cause is that in `pg-mem` when a constraint is being dropped the field `usedInIndexes` in the column representation is [not updated](https://github.com/oguimbal/pg-mem/blob/master/src/schema/schema.ts#L469). When adding the constraint the system creates an index and that field [is updated](https://github.com/oguimbal/pg-mem/blob/master/src/table.ts#L629). This is why when the column is dropped in the next statement of our test, the system sees the `REL_constraint` index inside `usedInIndexes` and tries to drop it.

**Comment by krumft** [comment]
Raised https://github.com/oguimbal/pg-mem/pull/308 to fix this.

**Comment by oguimbal** [comment]
Hi !

Thanks for the PR, I released it as `pg-mem@2.6.9`

**Comment by krumft** [comment]
Great, thank you!
