### ISSUE TITLE
Cannot parse FROM( SELECT ...) in SELECT queries

### ISSUE THREAD

**Issue by ValeriaVG** [oguimbal/pg-mem#47]
Thank you for an amazing library, works like a charm for common cases.

However, I've encountered a parse error, trying to parse the following query:
```sql
SELECT * FROM table_name as t,(SELECT COUNT(*) as count FROM table_name) as c
```
The query itself is valid, as you can see on the screenshot:
<img width="1263" alt="Screenshot 2021-01-30 at 21 40 33" src="https://user-images.githubusercontent.com/5821189/106367581-f045d880-6343-11eb-9bf7-7f57e5cb7534.png">

Here's the full error and stack:
```
 Error: 💔 Your query failed to parse.
This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error.

👉 Failed query:

    SELECT * FROM templates as t,(SELECT COUNT(*) as count FROM templates) as c LIMIT 20;

💀 Syntax error at line 1 col 26:

  SELECT * FROM styles as t,
                           ^
Unexpected comma token: ",". Instead, I was expecting to see one of the following:

    - A "kw_left" token
    - A "kw_right" token
    - A "kw_full" token
    - A "kw_inner" token
    - A "kw_where" token
    - A "kw_group" token
    - A "kw_join" token
    - A "kw_order" token
    - A "kw_limit" token
    - A "kw_offset" token
    - A "kw_fetch" token
    - A "kw_union" token
    - A "semicolon" token


      at Object.parseSql (node_modules/pg-mem/src/parse-cache.ts:44:15)
      at DbSchema.parse (node_modules/pg-mem/src/schema.ts:80:16)
      at DbSchema.queries (node_modules/pg-mem/src/schema.ts:88:31)
      at queries.next (<anonymous>)
      at DbSchema.query (amp-cms/src/schema.ts:67:20)
      at amp-cms/src/mocks.ts:8:17
      at Generator.next (<anonymous>)
      at amp-cms/src/mocks.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (src/mocks.ts:4:12)



error Command failed with exit code 1.
```

**Comment by oguimbal** [comment]
Hi !

Thanks, it's always pleasant to read that :)

That's a cross join (a carthesian product between those two tables), which is unsupported, but being implemented.

I'm closing this issue as a dupplicate of #26, feel free to subscribe to it to get news !

Thanks for the report.
