### ISSUE TITLE
QueryFailedError: column "columns.table_name" does not exist

### ISSUE THREAD

**Issue by shahyar** [oguimbal/pg-mem#67]
Hey there. I'm trying to run pg-mem in Jest. The bulk of the following code is taken directly from this repository, and fails to run with this error:

```
    QueryFailedError: column "columns.table_name" does not exist

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement:
                SELECT columns.*,
                  pg_catalog.col_description(('"' || table_catalog || '"."' || table_schema || '"."' || table_name || '"')::regclass::oid, ordinal_position) AS description,
                  ('"' || "udt_schema" || '"."' || "udt_name" || '"')::"regtype" AS "regtype",
                  pg_catalog.format_type("col_attr"."atttypid", "col_attr"."atttypmod") AS "format_type"
                  FROM "information_schema"."columns"
                  LEFT JOIN "pg_catalog"."pg_attribute" AS "col_attr"
                  ON "col_attr"."attname" = "columns"."column_name"
                  AND "col_attr"."attrelid" = (
                    SELECT
                      "cls"."oid" FROM "pg_catalog"."pg_class" AS "cls"
                      LEFT JOIN "pg_catalog"."pg_namespace" AS "ns"
                      ON "ns"."oid" = "cls"."relnamespace"
                    WHERE "cls"."relname" = "columns"."table_name"
                    AND "ns"."nspname" = "columns"."table_schema"
                  )
                WHERE
                ("table_schema" = 'public' AND "table_name" = 'thing');

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at PostgresQueryRunner.<anonymous> (src/driver/postgres/PostgresQueryRunner.ts:228:19)
      at step (node_modules/tslib/tslib.js:141:27)
      at Object.throw (node_modules/tslib/tslib.js:122:57)
      at rejected (node_modules/tslib/tslib.js:113:69)
```

```typescript
import { IMemoryDb, newDb } from 'pg-mem'
import { BaseEntity, Column, Connection, Entity, PrimaryColumn } from 'typeorm'

@Entity()
class Thing extends BaseEntity {
    @PrimaryColumn({ type: 'uuid' })
    id: string

    @Column()
    name: string
}

interface Ctor<T> extends Function {
    new(...params: any[]): T; prototype: T;
}
interface TypeOrmTest {
    db: Connection;
    mem: IMemoryDb;
    many: (sql: string) => any[];
    one: (sql: string) => any;
    none: (sql: string) => void;
}

async function typeOrm(
    title: string,
    entities: () => Ctor<BaseEntity>[],
    setup: ((mem: TypeOrmTest) => any) | null,
    fn: (data: TypeOrmTest) => Promise<any>
) {
    it(title, async () => {
        const mem: IMemoryDb = newDb({
            autoCreateForeignKeyIndices: true,
        });
        const many = mem.public.many.bind(mem.public);
        const none = mem.public.none.bind(mem.public);
        const one = mem.public.one.bind(mem.public);
        const db: Connection = await mem.adapters.createTypeormConnection({
            type: 'postgres',
            entities: entities(),
        });
        const key = { db, mem, many, none, one };
        setup?.(key);
        try {
            await db.synchronize();
            await fn(key);
        } finally {
            await db.close()
        }
    });
}

describe('Thing entity', () => {
    typeOrm('just works', () => [Thing], null, async ({ db }) => {
        db.getRepository(Thing);
    });
})
```

**Comment by oguimbal** [comment]
Hi ! Thanks for the report.

I believe this must be a dupplicate of #61 ... please reopen the issue if I'm mistaken !
