### ISSUE TITLE
the Postgresql word "time" is unrecognized by the sql parser

### ISSUE THREAD

**Issue by echouvet** [oguimbal/pg-mem#83]
I tried to get feed my database's schema into pg-mem from a file using the following 
```ts
  db.public.none(fs.readFileSync(fileName, "utf8"));
```
my file has the following table: 
```sql
create table ws (
    id         uuid primary key default gen_random_uuid(),
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    updated_at timestamp without time zone not null default (now() at time zone 'utc'),
    name text not null
);
```
I got the following error message: 
```
     Error: 💔 Your query failed to parse.
This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error.

👉 Failed query:

    create table ws
(
    id         uuid primary key default gen_random_uuid(),
    created_at timestamp without time zone not null default (now() at TIME zone 'utc'),
    updated_at timestamp without time zone not null default (now() at TIME zone 'utc'),

    name text not null
);
;

💀 Syntax error at line 4 col 71:

      created_at timestamp without time zone not null default (now() at TIME
                                                                        ^
Unexpected word token: "time". I did not expect any more input. Here is the state of my parse table:

    kw_between → %word ● 
    kw_operator → %word ●

      at Object.parseSql (node_modules/pg-mem/src/parse-cache.ts:44:15)
      at DbSchema.parse (node_modules/pg-mem/src/schema.ts:80:16)
      at DbSchema.queries (node_modules/pg-mem/src/schema.ts:88:31)
      at queries.next (<anonymous>)
      at DbSchema.query (node_modules/pg-mem/src/schema.ts:67:20)
      at DbSchema.none (node_modules/pg-mem/src/schema.ts:52:14)
      at runSqlFile (test/setup/mongo_setup.test.ts:9:21)
      at Context.<anonymous> (test/setup/mongo_setup.test.ts:27:3)
      at processImmediate (node:internal/timers:463:21) 
```

**Comment by oguimbal** [comment]
Hi !

Thanks for the report.

I dont have much time these days, but i'll try to look into this asap !
