### ISSUE TITLE
SHOW SERVER_VERSION; is giving a error SequelizeDatabaseError: unrecognized configuration parameter "[object Object]"

### ISSUE THREAD

**Issue by victor-perez** [oguimbal/pg-mem#88]
SequelizeDatabaseError: unrecognized configuration parameter "[object Object]"

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: SHOW SERVER_VERSION;

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at Query.formatError (node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
      at Query.run (node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
      at node_modules/sequelize/lib/sequelize.js:619:16
      at PostgresQueryInterface.databaseVersion (node_modules/sequelize/lib/dialects/abstract/query-interface.js:128:12)
      at Sequelize.databaseVersion (node_modules/sequelize/lib/sequelize.js:873:12)
      at node_modules/sequelize/lib/dialects/abstract/connection-manager.js:260:31
      at ConnectionManager.getConnection (node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
      at node_modules/sequelize/lib/sequelize.js:613:26
      at PostgresQueryInterface.select (node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
      at Function.findAll (node_modules/sequelize/lib/model.js:1753:21)

**Comment by oguimbal** [comment]
Hi !

Oops... the `show` statement had no test, and it seems it never worked !

This should be fixed with `pg-mem@1.8.5`
