### ISSUE TITLE
MikroOrm Adapter throws DriverException when using limit

### ISSUE THREAD

**Issue by cbadger85** [oguimbal/pg-mem#97]
Hello! I'm trying to write some integration tests in Jest for with `mikro-orm` and `pg-mem`, but when calling any repository method with `limit` (`findOneOrFail`, `findOne`, `find` with a limit and offset), it throws a `DriverException`. It works fine when connecting to my local pg database, just not with pg-mem.

code snippet
```ts
import {
  BaseEntity,
  DriverException,
  EntitySchema,
  MikroORM,
} from '@mikro-orm/core';
import { EntityRepository } from '@mikro-orm/postgresql';
import { IBackup, newDb } from 'pg-mem';

export class Book extends BaseEntity<Book, 'id'> {
  id!: number;
  title!: string;
  author!: string;
}

export const bookSchema = new EntitySchema<Book, BaseEntity<Book, 'id'>>({
  class: Book,
  extends: 'BaseEntity',
  properties: {
    id: { type: Number, primary: true },
    title: { type: 'string' },
    author: { type: 'string' },
  },
});

class BookService {
  constructor(private bookRepository: EntityRepository<Book>) {}

  async findBookById(id: number) {
    return await this.bookRepository.findOneOrFail({ id });
  }
}

let orm: MikroORM;
let bookService: BookService;
let bookRepository: EntityRepository<Book>;
let backup: IBackup;

beforeAll(async () => {
  const db = newDb();
  orm = await db.adapters.createMikroOrm({
    entities: [bookSchema],
    debug: true,
  });

  await orm.getSchemaGenerator().createSchema();

  bookRepository = orm.em.getRepository(bookSchema);
  bookService = new BookService(bookRepository);
  backup = db.backup();
});

beforeEach(async () => {
  orm.em.clear();
  backup.restore();
});

describe('Sample Test', () => {
  it('should throw an error if the book does not exist', async () => {
    const book = bookService.findBookById(1);

    book.catch(console.error);

    await expect(book).rejects.toBeInstanceOf(Error);
    await expect(book).rejects.not.toBeInstanceOf(DriverException);
  });
});

```

stack trace with debug statements
```bash
    [discovery] ORM entity discovery started, using ReflectMetadataProvider
    [discovery] - processing entity Book
    [discovery] - processing entity BaseEntity
    [discovery] - entity discovery finished, found 2 entities, took 250 ms
    [info] MikroORM successfully connected to database public on postgresql://postgres@127.0.0.1:5432
    [query] select 1 from pg_database where datname = 'public' [took 9 ms]
    [query] set names 'utf8'; [took 1 ms]
    [query] set session_replication_role = 'replica'; [took 3 ms]
    [query] create table "book" ("id" serial primary key, "title" varchar(255) not null, "author" varchar(255) not null); [took 6 ms]
    [query] set session_replication_role = 'origin'; [took 3 ms]
    [query] select "e0".* from "book" as "e0" where "e0"."id" = 1 limit 1 [took 10 ms]

    DriverException: select "e0".* from "book" as "e0" where "e0"."id" = 1 limit 1 - Unknown alias "[object Object]"
    
    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.
    
    *️⃣ Failed SQL statement: select "e0".* from "book" as "e0" where "e0"."id" = 1 limit 1;
    
    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:
    
    
        at PostgreSqlExceptionConverter.convertException (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
        at PostgreSqlExceptionConverter.convertException (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
        at PgMemDriver.convertException (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
        at /Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
        at PgMemDriver.find (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
        at PgMemDriver.findOne (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)
        at SqlEntityManager.findOne (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/EntityManager.js:227:22)
        at SqlEntityManager.findOneOrFail (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/EntityManager.js:244:24)
        at BookService.findBookById (/Users/cbadger85/Desktop/mikro-orm-test/service/src/__tests__/content-manager/common/services/sample-test.spec.ts:30:12)
    
    previous Error: select "e0".* from "book" as "e0" where "e0"."id" = 1 limit 1 - Unknown alias "[object Object]"
    
    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.
    
    *️⃣ Failed SQL statement: select "e0".* from "book" as "e0" where "e0"."id" = 1 limit 1;
    
    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:
    
    
        at buildCols (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/transforms/selection.ts:91:27)
        at buildCols.next (<anonymous>)
        at new Selection (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/transforms/selection.ts:129:29)
        at Object.buildSelection (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/transforms/selection.ts:32:12)
        at EqFilter.select (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/transforms/transform-base.ts:68:20)
        at DbSchema.buildSelect (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:1161:23)
        at DbSchema.prepareWithable (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:440:47)
        at DbSchema.executeWithable (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:453:25)
        at DbSchema._execOne (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:165:33)
        at /Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:118:31
        at Object.pushContext (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/utils.ts:382:16)
        at DbSchema.queries (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:115:47)
        at queries.next (<anonymous>)
        at DbSchema.query (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/schema.ts:84:20)
        at MemPg.query (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/pg-mem/src/adapters.ts:113:76)
        at /Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/knex/lib/dialects/postgres/index.js:237:18
        at new Promise (<anonymous>)
        at Client_PG._query (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/knex/lib/dialects/postgres/index.js:236:12)
        at Client_PG.knex_1.Client.query (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:168:25)
        at Runner.query (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/knex/lib/runner.js:151:36)
        at /Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/knex/lib/runner.js:40:23
        at /Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/knex/lib/runner.js:277:24
        at PgMemConnection.executeQuery (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/connections/Connection.js:56:25)
        at PgMemConnection.execute (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:105:21)
        at QueryBuilder.execute (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/query/QueryBuilder.js:300:21)
        at PgMemDriver.find (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
        at PgMemDriver.findOne (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)
        at SqlEntityManager.findOne (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/EntityManager.js:227:22)
        at SqlEntityManager.findOneOrFail (/Users/cbadger85/Desktop/mikro-orm-test/service/node_modules/@mikro-orm/core/EntityManager.js:244:24)
        at BookService.findBookById (/Users/cbadger85/Desktop/mikro-orm-test/service/src/__tests__/content-manager/common/services/sample-test.spec.ts:30:12) {
      data: { error: 'Unknown alias "[object Object]"', code: undefined },
      location: { start: 0, end: 0 }
    }
```

EDIT: I just tried it with `repository.findOne` and that one also throws the same exception if the row doesn't exist. I've also tried populating the table, with no luck.

EDIT 2: Ok, I think this bug has something to do with `limit`, because when I ran a test for paginated results I got the same error. I went ahead and updated the title of this issue and modified the description.

**Comment by oguimbal** [comment]
Hi !

Thanks for the detailed report 😎... this should be fixed with `pg-mem@1.9.3`

**Comment by cbadger85** [comment]
Thanks! All my tests are passing now! Great work on the library!

**Comment by oguimbal** [comment]
Thanks :)
